accordion/urls.py
from django.urls import path

from . import views

app_name = 'accordion'

urlpatterns = [
    path('', views.index, name='index'),
]

course/urls.py
from django.urls import path

from . import views

app_name = 'course'

urlpatterns = [
    path('', views.course_list, name='index'),
    path('addcourse/', views.create_course, name='add'),
    path('coursedetail/<str:key>/', views.course_detail, name='detail'),
    path('deletecourse/<str:key>/', views.delete_course, name='delete'),
    path('register/', views.register, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutPage, name='logout')
]

event/urls.py
from django.urls import path

from . import views

app_name = 'event'

urlpatterns = [
    path('', views.event_list, name='index'),
    path('register/<str:key>/', views.event_register, name='register'),
    path('deleted/<str:key>/', views.event_delete, name='delete'),
]

library/urls.py
from django.urls import path
from . import views

from . import views

app_name = 'library'

urlpatterns = [
    path('', views.index, name='index'),
    path("books/", views.return_data, name="books"),
]

terracourse/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('course.urls')),
    path('events/', include('event.urls')),
    path('accordion/', include('accordion.urls')),
    path('library/', include('library.urls')),
]

accordion/models.py
from django.db import models

# Create your models here.

course/models.py
from django.db import models

# Create your models here.
class Courses(models.Model):
    matkul = models.CharField(max_length=100, default="matkul")
    dosen = models.CharField(max_length=50, default="dosen")
    sks = models.IntegerField(default="3")
    deskripsi = models.TextField(null = True)
    semester = models.CharField(max_length=50, default="Gasal")
    ruang = models.CharField(max_length=50, null = True)

def __str__(self):
    return self.matkul

event/models.py
from django.db import models

# Create your models here.
class Event(models.Model):
    name = models.CharField(max_length=50)

    
class Participant(models.Model):
    name = models.CharField(max_length=50)
    event_registered = models.ForeignKey(Event, on_delete=models.CASCADE)

library/models.py
from django.db import models

# Create your models here.

course/forms.py
from django import forms
from .models import Courses
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from crispy_forms.helper import FormHelper


class courseform(forms.ModelForm):    
    class Meta:
        model = Courses
        fields = (
            "matkul",
            "dosen",
            "sks",
            "deskripsi",
            "semester",
            "ruang",
            )

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

event/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import Event, Participant

class Participantform(forms.ModelForm):    
    class Meta:
        model = Participant
        fields = ("name", "event_registered")
        widgets = {'event_registered': forms.HiddenInput()}

class Eventform(forms.ModelForm):    
    class Meta:
        model = Event        
        fields = ("name",)
        labels = {"name":_("Add new activity")}

accordion/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'accordion/index.html')

course/views.py
from django.shortcuts import render, redirect
from .forms import courseform, CreateUserForm
from .models import Courses
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def course_list(request):
    courses = Courses.objects.all()
    context = {"obj" : courses}
    return render(request, "course/index.html", context)

def create_course(request):
    form = courseform()
    if request.method == 'POST':
        form = courseform(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")

    context = {"form" : form}
    return render (request,"course/addcourse.html", context)

def course_detail(request, key):
    myid = Courses.objects.get(id=key)
    context = {"obj" : myid}
    return render(request, "course/coursedetail.html", context)

def delete_course(request, key):
    myid = Courses.objects.get(id=key)
    myid.delete()
    return redirect("/")

def register(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/admin/login/?next=/")

    context = {'form':form}
    return render(request, "course/register.html", context)

def loginPage(request):
    if request.user.is_authenticated:
        return redirect("/")

    else:
        if request.method == "POST":
            username = request.POST.get("username")
            password = request.POST.get("password")

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect("/")

        context = {}
        return render(request, "course/login.html", context)

def logoutPage(request):
    logout(request)
    return redirect("/")

event/views.py
from django.shortcuts import render, redirect
from django.forms import inlineformset_factory
from .models import Event,Participant
from .forms import Participantform, Eventform

# Create your views here.

def event_list(request):
    event = Event.objects.all()
    participant = Participant.objects.all()
    form = Eventform()
    if request.method == 'POST':
        form = Eventform(request.POST)
        if form.is_valid():
            form.save()
            return redirect('event:index')
    context = {"evt":event, "ptc":participant, "form":form}
    return render(request, "event/index.html", context)

def event_register(request, key):
    key = Event.objects.get(id = key)
    form = Participantform(initial={'event_registered':key})
    if request.method == 'POST':
        form = Participantform(request.POST)
        if form.is_valid():
            form.save()
            return redirect('event:index')

    context = {"form":form}
    return render(request, "event/register.html", context)

def event_delete(request, key):
    key = Event.objects.get(id=key)
    key.delete()
    return redirect('event:index')

library/views.py
from django.shortcuts import render, HttpResponse
from django.http import JsonResponse
import requests
import json

# Create your views here.
def index(request):
    return render(request, "library/index.html")

def return_data(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q']
    data = requests.get(url)
    books = json.loads(data.content)
    return JsonResponse(books, safe=False)

accordion/templates/accordion/index.html
<!doctype html>
{%load static%}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <link rel="stylesheet" href="{% static 'accordion/style.css' %}">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <title>Story7</title>
</head>
<body>
 
<div id="accordion">
  <div class ="wrapper">
    <div>
    <button value='up' class='up-button' >Up</button>
	<button value='down' class ='down-button'>Down</button>
    </div>
  <h3>Aktivitas </h3>
  <div>
    <p>
    kuliah.
    </p>
  </div>
  </div>

  <div class="wrapper">
    <div>
    <button value='up' class='up-button' >Up</button>
	<button value='down' class ='down-button'>Down</button>
    </div>
  <h3>Organisasi/Kepanitiaan</h3>
  <div>
    <p>
        <ul>
            <li>Sospro (kalo diitung kepanitiaan)</li>
            <li>Mentor DDP0 2020</li>
        </ul>
    </p>
  </div>
  </div>

  <div class ="wrapper">
    <div>
    <button value='up' class='up-button' >Up</button>
	<button value='down' class ='down-button'>Down</button>
    </div>
  <h3>Prestasi</h3>
  <div>
    <p>
        <ul>
            <li>65th place Low Tier City Midseason SEA</li>
            <li>13th place AUSSEA Open 4</li>
            <li>25th place RnWC Grand Series</li>
        </ul>
    </p>
  </div>
  </div>

  <div class ="wrapper">
    <div>
    <button value='up' class='up-button' >Up</button>
	<button value='down' class ='down-button'>Down</button>
    </div>
  <h3>Ngga tau mau isi apa lagi</h3>
  <div>
    <p>
    tapi di story disuruh 4, jadinya diisi ginian aja
    </p>
  </div>
  </div>
</div>

 <script src="{%static "accordion/script.js"%}"></script>
</body>
</html>

course/templates/course/addcourse.html
{% extends 'course/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="POST" , action="">
        {% csrf_token %}
        {{form | crispy}}
      
        <input type="Submit" value="Submit">
    </form>
{% endblock %}

course/templates/course/base.html
<!DOCTYPE html>
<html lang="en">
{%load static%}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'course/style.css' %}">
    

    <title>Story5</title>
  </head>

  <body>
     <nav class="navbar sticky-top navbar-inverse navbar-expand-lg navbar-light" style="background-color: #74c69d">
      <div class="container-fluid">
      <a class="navbar-brand">Welcome!</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="nav navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{%url 'course:index'%}">Course List</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{%url 'course:add'%}">Add Course</a>
          </li>
          {% endif %}
        </ul>

        {% if user.is_authenticated %}
        <ul class="nav navbar-nav navbar-right ml-auto">
          <li>
            <a class="nav-link">Hello, {{user.get_username}}</a>
          </li>
          <li>
            <a class="nav-link" href="{%url 'course:logout'%}">Logout</a>
          </li>   
        </ul>

        {% else %}
        <ul class="nav navbar-nav navbar-right ml-auto">
          <li>
            <a class="nav-link" href="{%url 'course:register'%}">Sign Up</a>
          </li>
          <li>
            <a class="nav-link" href="{%url 'course:login'%}">Login</a>
          </li>   
        </ul>
        {% endif %}

      </div>
      </div>
    </nav>
    <div class="d-flex flex-column my-flex-container">      
      {%block content%}
      
      {% endblock %}
    </div>
      {% block footer %}
      
      {% endblock footer %}  

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

course/templates/course/coursedetail.html
{% extends 'course/base.html' %}

{% block content %}
<table border="1px">
    <tbody>
        <td align="center"><b>Mata kuliah</b></td>
        <td align="center">{{obj.matkul}}</td>
    </tbody>
    <tbody>
        <td align="center"><b>Dosen</b></td>
        <td align="center">{{obj.dosen}}</td>
    </tbody>
    <tbody>
        <td align="center"><b>Jumlah SKS</b></td>
        <td align="center">{{obj.sks}}</td>
    </tbody>
    <tbody>
        <td align="center"><b>Deskripsi</b></td>
        <td align="center">{{obj.deskripsi}}</td>
    </tbody>
    <tbody>
        <td align="center"><b>Semester</b></td>
        <td align="center">{{obj.semester}}</td>
    </tbody>
    <tbody>
        <td align="center"><b>Ruang</b></td>
        <td align="center">{{obj.ruang}}</td>
    </tbody>
</table>
<center><a href="{% url 'course:delete' key=obj.id %}" class="btn btn-danger" id="justify">Delete</a></center>
{% endblock %}

course/templates/course/index.html
{% extends 'course/base.html' %}

{% block content %}
<table border="1px">
    <body>
        <td align="center"><b>Nama Matkul</b></td>
        <td align="center"><b>Nama Dosen</b></td>
        <td align="center"><b>Detail</b></td>
    </body>
    {% for i in obj %}
    <tbody>
        <td align="center">{{i.matkul}}</td>
        <td align="center">{{i.dosen}}</td>
        <td align="center"><a href="{%url 'course:detail' key=i.id%}">Detail</td>
    </tbody>
    {% endfor %}
</table>
{% endblock %}

{% block footer %}
{% if user.is_authenticated %}

{% else %}
    <div id="justify">
        <h1>Login to add your own course!</h1>
    </div>
{% endif %}
{% endblock footer %}

course/templates/course/login.html
{% extends 'course/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div id="justify">
<form method="POST" action="">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Username..." class="form-control">
    <input type="password" name="password" placeholder="Password..." class="form-control" >
    <input type="submit" name="Create User">
</form>
</div>
{% endblock %}

course/templates/course/register.html
{% extends 'course/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div id="justify">
<form method="POST" action="">
    {% csrf_token %}
    {{form | crispy}}
    <input type="submit" name="Create User">
</form>
</div>
{% endblock %}

event/templates/event/base.html
<!DOCTYPE html>
<html lang="en">
{%load static%}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'event/style.css' %}">

    <title>Story5</title>
  </head>

  <body>   
      {%block content%}
      
      {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

event/templates/event/index.html
{% extends 'event/base.html' %}

{% block content %}
<h1>Activities</h1>
<br>
<div class = "column">
{% for i in evt %}
<div class = "col-auto">
    <div class = "card text-white mb-3 my-card", style = "width: 50%">
        <div class = "card-body">
            <h5 class = "card-title">{{i.name}}</h5>
            <ul>
            {% for j in ptc %}
                {% if j.event_registered.name == i.name %}
                    <p class = "card-text"><li>{{j.name}}</li><p>
                {% endif %}
            {% endfor %}
            </ul>
            <a href="{% url 'event:register' key=i.id %}" button type="button" class="btn btn-light">Register</a>
            <a href="{% url 'event:delete' key=i.id %}" button type="button" class="btn btn-danger">Delete</a>
        </div>
    </div>
</div>   
{% endfor %}
<div class = column>
    <div class = "col-auto">
        <div class = "card text-white mb-3 my-card", style = "width: 50%">
            <div class "card-body">
                <form method="POST" , action="">
                    {% csrf_token %}
                    {{form}}
                    <input type="Submit" value="Submit">
                </form>
            </div>
        </div>
    </div>
<div>
{% endblock  %}

event/templates/event/register.html
{% extends 'event/base.html' %}

{% block content %}
<div class="d-flex flex-column my-flex-container">
     <form method="POST" , action="">
        {% csrf_token %}
        {{form}}      
        <input type="Submit" value="Submit">
    </form>
    <a href="{% url 'event:index' %}" button type="button" class="btn btn-danger">Cancel</a>
</div>
{% endblock  %}

library/templates/library/index.html
<!doctype html>
{%load static%}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="{% static 'event/style.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <title>Story8</title>
</head>
<body>
  <input id="keyword" placeholder="Search..">

  <div id=res>

  </div>
  <script type="text/javascript">
  $("#keyword").keyup(function() {
    var key = $("#keyword").val();
    console.log(key);

    $.ajax({
        url: "{% url 'library:books'%}" + "?q=" + key,
        success:function(res){
            console.log(res.items);
            var obj_res = $("#res");
            obj_res.empty();

            for (i=0;i<res.items.length;i++){
                var title = res.items[i].volumeInfo.title;
                var thumbnail = res.items[i].volumeInfo.imageLinks.thumbnail;
                var author = res.items[i].volumeInfo.authors;
                var info = res.items[i].searchInfo.textSnippet;
                console.log(title);
                obj_res.append(
                  "<div class = 'card mb-3 my-card', style = 'width: 50%'>"+
                    "<div class = 'card-body'>"+
                    "<h5 class = 'card-title' id='justify'>"+title+"</h5>"+
                      "<table>"+
                        "<tbody>"+
                          "<tr>"+
                            "<td rowspan='2'><img src="+thumbnail+"></img></td>"+
                            "<td>"+author+"</td>"+
                          "<tr>"+
                            "<td>"+info+"</td>"+
                        "</tbody>"+
                      "</table>"+
                    "</div>"+
                  "</div>");
            }
        }
    });
  });
  </script>
</body>
</html>



 {% comment %} "<div class = 'card text-white mb-3 my-card', style = 'width: 50%'>"+
                    "<div class = 'card-body'>"+
                        "<h5 class = 'card-text' id='justify'>"+title+"</h5>"+
                        "<p class = 'card-text' id='justify'>"+author+"</p>"+
                        "<img src="+ thumbnail +"></img>"+
                    "</div>"+
                  "</div>" {% endcomment %}


{% comment %} "<li>"+title+"<br>"+author+"<br> <img src="+thumbnail+"></li>" {% endcomment %}